# Generated by Django 5.0.7 on 2024-07-18 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_programme_tuitionfee_programmeid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tuitionfee',
            old_name='programmeId',
            new_name='programme',
        ),
    ]
