# Generated by Django 5.0.7 on 2024-07-20 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_student_programme'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tuitionfee',
            old_name='tuitionFee',
            new_name='amount',
        ),
    ]
