# Generated by Django 5.0.7 on 2024-07-20 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_tuitionfee_tuitionfee_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tuitionfee',
            old_name='amount',
            new_name='fee',
        ),
        migrations.AlterField(
            model_name='student',
            name='tuitionFee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tuitionFee', to='api.tuitionfee'),
        ),
    ]
