#GitHub ActionsAutomatically created by GitHub Actions
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12.3]

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: verceldb_github
          POSTGRES_USER: default
          POSTGRES_PASSWORD: Qm6AXbC4vwRB
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      env:
        DB_NAME: test_verceldb_github
        DB_USER: default
        DB_PASSWORD: zuUo4Xtqy5nI
        DB_HOST: ep-bold-cloud-a70ec02k.ap-southeast-2.aws.neon.tech
        DB_PORT: 5432
      run: |
        python manage.py test